---
number:     10
title:      Open for Change (Onawi, 40 Fires, Bristol Braille Technology)
description: |
            <p>A great deal of open source hardware is built by engineers for engineers, and comprises mostly electronics and/or computing technology.  Which is not at all surprising given the origins of the movement and where we are on the adoption curve. However, a growing number of projects are seeking to tackle ever more challenging problems and working with an increasingly broader selection of technologies.</p> 

             <p>At the tenth OSHUG meeting we will hear from Onawi, a non-profit that is working to deliver liberally licensed wind turbine technology, 40 Fires, a foundation that is building an open source hydrogen fuel cell electric car, and from Bristol Braille Technology, who are considering the possibility of an open source Braille display.</p>

sessions: |
            <h3>Open Renewables</h3>
            <p id="Onawi"> .</p>
            <p id="JavierRuiz" class="vcard">Javier Ruiz... </p>

             <h3>An open source approach to developing energy-efficient technology</h3>
             <p id="40Fires">Two years ago start-up company <a title="Riversimple" href="http://www.riversimple.com/">Riversimple</a> unveiled a ground-breaking vehicle that has the potential to transform the auto industry. The Riversimple urban vehicle, due to be in production in 2014, is lightweight, powered by hydrogen and capable of 300 mpg (energy equivalent).  As part of its strategy, Riversimple announced the establishment of an independent open source foundation, <a title="40 Fires" href="http://www.40fires.org/">40 Fires</a>, that would make available the designs for the car on-line under an open source license. Two years on, the 40 Fires team report on the joys, trials and tribulations of working on a potentially game-changing project in one of the world's biggest industries.</p>
             <p id="PatrickAndrews" class="vcard">Patrick Andrews is project leader of the 40 Fires Foundation and a board member of eco-car company Riversimple. A former corporate lawyer with Kingfisher and Pratt & Whitney, he now spends his time pursuing an interest in social innovation, with a particular focus on alternative business models and governance structures.</p>

             <h3>Developing a revolutionary, affordable Braille Cell Display</h3>
             <p id="BristolBrailleTechnology">Braille usage has been shown to have a strong correlation with employment&mdash;and by extension <em>independence</em>&mdash;amongst the blind. However Braille usage is stagnating under a lack of technical innovation which has left it hugely expensive and uncommon.</p>
             <p><a title="Bristol Braille Technology" href="http://www.bristolbrailletechnology.com/">Bristol Braille Technology</a> was founded on the 6th of January, 2011, when the first meeting of interested professionals met to discuss the need for more affordable refreshable Braille. We are currently designing our first prototype cell display. Our aim is to make a Braille cell display7mdash;that is a tactile 'screen' which connects to a computing device&mdash;which, unlike the current models, is affordable to the majority of blind individuals in the UK and, eventually, anywhere around the world.</p>
              <p id="EdRogers" class="vcard">Ed Rogers is a Bristolian and recent graduate from the University of the West of England where he studied Animation and Interactive Design. During this course he first began to consider the issue of digital Braille. After leaving university he continued to pursue the goal of an affordable Braille cell display, eventually founding the not-for-profit Community Interest Company, Bristol Braille Technology.</p>

             <p><b>Note: Please aim to arrive for 18:00 - 18:20 as the event will start at 18:30 prompt.</b></p>

date:        19th May 2011
dtstart:     2011-05-19:T18:00Z
dtend:       2011-05-19:T20:00Z
start:       18:00
end:         20:00
pubdate:     Tue, 19 April 2011 21:18:00 BST
location:    Centre for Creative Collaboration
isoduration: P0Y0M0DT02H00M00S
generator:   vi
registration: http://skillsmatter.com/event/java-jee/oshug-open-source-chips/js-1481
upcoming:     http://upcoming.yahoo.com/event/7905331/
lanyrd:       http://lanyrd.com/2011/oshug9/

tags:
    - OSHUG
    - OpenSource
    - hardware
    - opensourcehardware
    - openhardware
    - community
    - renewables
    - turbine
    - hydrogencar
    - braille
    - Onawi
    - 40Fires
    - BristolBrailleTechnology
    - turbine
    - CentreforCreativeCollaboration
