---
number:     11
title:      (Canterbury)
description: |
             <p>For our 11<sup>th</sup> meeting, we are visiting <a href="http://www.eda.kent.ac.uk/">School of Engineering and Digital Arts</a> of <a href="http://www.kent.ac.uk/">The University of Kent</a>, home of the <a href="http://www.concurrency.cc/">concurrent.cc</a> project. <a href="http://traintimes.org.uk/London/Canterbury/18:00a/2011-6-23/21:45/2011-6-23/">Trains run regularly to and from central London</a> and take approximately an hour.</p>

sessions: |
            <h3>Open Source Hardware Collaboration</h3>
            <p id="Collaboration">An assesment of the current state of the art in hardware collaboration through a tour of a series of Open Source Hardware projects. How easy is it to discover projects, view and understand their designs,  build your own version and conribute changes back?</p>
            <p id="PaulDowney" class="vcard"><a class="fn url" title="Paul Downey" href="http://blog.whatfettle.com">Paul Downey</a> (<a href="http://twitter.com/psd" class="nickname">psd</a>) is a <a href="http://thewebisagreement.com">doodling</a> software hacker, formally a member of <a href="http://osmosoft.com">Osmosoft</a> a small Open Source software team where he represented <a href="http://bt.com">BT</a> at the <a href="http://www.w3.org">W3C</a>, is a co-organiser of <a href="http://oshug.org">OSHUG</a> and a co-founder of <a href="http://solderpad.com" class="org">SolderPad</a>, a collaboration system for electronics systems.</p>


             <p><b>Note: Please aim to arrive for 18:00 - 18:20 as the event will start at 18:30 prompt.</b></p>

date:        23rd June 2011
dtstart:     2011-06-23:00Z
dtend:       2011-06-23:00Z
start:       18:00
end:         20:00
pubdate:     Tue, 24 May 2011 21:18:00 BST
location:    'School of Engineering and Digital Arts'
isoduration: P0Y0M0DT02H00M00S
generator:   vi
registration: 
upcoming:     
lanyrd:       http://lanyrd.com/2011/oshug11/

tags:
    - OSHUG
    - OpenSource
    - hardware
    - opensourcehardware
    - openhardware
    - community
    - UniversityOfKent
