---
number:     12
title:      Practical Approaches (Double-sided PCB Design, Controlling Power, 3W RGB LED Controller )
description: |
             <p>Developing a solution to a problem is not simply a matter of whether it is technically possible, but can involve all manner of challenging constraints. This is particularly the case in DIY and small-scale manufacture contexts, as there may be limited access to tools, test equipment and costly fabrication processes.</p>

             <p>At the twelfth OSHUG meeting we'll be hearing about practical approaches that were developed in tackling three different problems. One is concerned with designing a double-sided PCB to accommodate 0.5mm pitch surface mount devices, that can be reliably built using low cost DIY methods. Another with safely controlling mains powered devices from the Internet, and the third with building a 3W RGB LED controller using all open source design and development tools.</p> 

sessions: |
            <h3>DIY Double-sided PCB Design and Development for embedded ARM</h3>
            <p id="DIYDSPCB">Inspired by the success of the Arduino platform and driven by a recognition that to go from raw materials to a working system is both exciting and empowering, a project was born to develop a powerful microcontroller board that can be built from scratch. With this came the challenge of designing a double-sided PCB that will accommodate a 64-pin LQFP package on 0.5mm pitch, and that can be built using low cost DIY techniques.</p>
            <p>In this talk we will learn about the rules which needed to be applied in order to ensure that construction of such a PCB is practical, and discoveries that were made in its development.</a>
            <p id="GarryBulmer" class="vcard"><a class="fn url" title="Garry Bulmer - Blog" href="http://ourduino.wordpress.com">Garry Bulmer</a> gained his degree in Computer Science in the early 1980s and developed software for companies including ICL, before going on to teach Computer Science and Software Engineering at degree level and beyond. During the 1990s he was a co-founder of Parallax Solutions, a software services company with customers that included Rover Group and Rolls Royce, and that partnered with Sun Microsystems and delivered their Enterprise Architecture Blueprints. He's since held the position of Chief Architect at Keane, Aspen Technology and Caritor. More recently he has become involved in education, running Arduino workshops for local schools and at events including Howduino, DEV8D and fizzPop.</p>

             <h3>A Simple Approach to Controlling Power from Internet Apps</h3>
             <p id="HomePower">Working with mains power can be a daunting prospect and requires due care and attention. In this presentation we will hear about a simple and safe way to control mains-powered appliances from the Internet using cheap wireless links. This will include a live demo based on MBED and an explanation of this approach, and there will be opportunity to discuss its pros and cons.</p>
             <p id="PaulTanner" class="vcard"><a class="fn url" title="Paul Tanner - Twitter" href="http://twitter.com/paul_tanner">Paul Tanner</a> is a consultant, developer and maker in wood, metal, plastic, electronics and software.  His day job is IT-based business improvement for SMEs. By night he turns energy nut, creating tools to optimise energy use. Paul graduated in electronics and was responsible for hardware and software product development and customer services in several product and service start-ups, switching to consulting in 2000.</p>

             <h3>Using Open Source tools to design and build a 3W RGB LED Controller in a month of Sundays</h3>
             <p id="RGBLED">There are many Open Source and freely available hardware designs but almost all of them are currently hosted by proprietary tool chains. Whether it's the EDA suite used to design the boards, the compilers used to build the firmware or the dongles used to flash the firmware, the chances are that at least one, if not all, are under a non-free license of some kind.</p>
             <p>In this talk we will hear about the experience of using an entirely open toolchain to develop a 3W RGB LED controller. Specifically, the the trials and tribulations in using Kicad: the GPL PCB Suite; AVR-GCC: the GNU Compiler Collection build that targets the Atmel AVR line of microcontrollers and a parallel port programmer that can be built in 5 minutes with minimal components.</p>
             <p id="AndyBennett"><span class="vcard"><span class="fn">Andy Bennett</span></span> is an Engineer that likes to inhabit the void between hardware and the software that runs on it. After graduating from Imperial College with a degree in Electronic & Electrical Engineering he joined Access Devices Digital Limited where he designed software and FPGA cores for the UK's first Dual Tuner Personal Video Recorders. He continued working on Advanced Product Development at Pace Micro Technology before leaving to become employee number 2 at GenieDB where he applies his finely honed ability to produce software on a shoestring.</p>
             <p>In his spare time he likes to design ambitious projects from scratch. In between prototyping designs for his own PDA, digital watch and bluetooth headset, he's currently building a two wheeled, actively balanced, robot.</p>

             <p><b>Note: Please aim to arrive for 18:00 - 18:20 as the event will start at 18:30 prompt.</b></p>

date:        29th September 2011
dtstart:     2011-09-29T18:00:00Z
dtend:       2011-09-29T20:00:00Z
start:       18:00
end:         20:00
pubdate:     Fri, 8 July 2011 10:20:00 BST
updated:     2011-09-08T00:00:00Z
location:    Centre for Creative Collaboration
isoduration: P0Y0M0DT02H00M00S
generator:   vi
registration: http://oshugpractical.eventbrite.com/
upcoming:     
lanyrd:       http://lanyrd.com/2011/oshug12/

tags:
    - OSHUG
    - OpenSource
    - hardware
    - opensourcehardware
    - openhardware
    - community
    - Pachube
    - CentreforCreativeCollaboration
    - ARM
    - mbed
    - PowerControl
    - KiCAD
    - RGBLED
    - GCC

