---
number:     19
title:       Kits (Homesense, Quick2Wire)
description: |
             <p>For those that are new to hardware development it can prove a daunting prospect, and kits that address the needs of those with little or no experience in this area have a vital role to play. At the nineteenth OSHUG meeting we will be hearing about two such kits, one that was designed to support user-led smart home innovation and that was based around the Arduino platform, and an experimenters kit for the Raspberry Pi that is currently in development.</p>

sessions: |
            <h3>The Homesense Project</h3>
            <p id="Homesense"><a href="http://www.designswarm.com/homesense/" title="The Homesense Project">The Homesense project</a> was a European user-led, smart-home development project employing open source hardware. The project was led by Tinker London and EDF and engaged households supported by local experts in the design and development of smart home concepts.</p>
            <p>The project was developed as a reaction to top-down design approaches commonly observed in technological development and home building. Most early research viewed smart homes as a single complex system that is designed and constructed from the ground up, and assumes that most aspects (physical building, digital infrastructure, furniture, appliances) are under the control of a single smart-home developer. (Kortuem et al. 2010)</p>
            <p>In the contrasting reality however of multi-vendor development and retrofitting this is rarely the case. Inspired also by an argument that smart homes are developed by experts in a top down approach subsequently living with a smart home is acknowledged to be problematic to non-experts who lack control over respective technologies.</p>
            <p>The Homesense project was therefore designed to enable user-led innovation within the home environment, building alongside existing environmental and social conditions allowing end-users to address their own concerns in their physical and ‘lived in’ space. Homesense sought to bring the open collaboration methods of online communities to physical infrastructures in the home. Designing a toolkit to support this approach is explored as a topic of this presentation.</p>
            <p id="NatashaCarolan" class="vcard"><a class="fn url" title="Natasha Carolan" href="http://twitter.com/NatashaCarolan/">Natasha Carolan</a> is a PhD student at HighWire Doctoral Training Centre, Lancaster University where her research considers commodification of design and production processes in the digital economy. A product designer by background, her research explores open and user innovation, service design and value co-creation in areas of NPD and manufacturing. Natasha co-designed the Homesense toolkit by situating the toolkit as a cultural probe a strategy that Natasha believes is important in placing open source hardware in a democratic system as a tool for learning and empowerment.</p>

             <h3>Quick2Wire</h3>
             <p id="Quick2Wire"><a href="http://quick2wire.com/">Quick2Wire Limited</a> is a start-up that is developing a range of OSH/OSS add-on products for the Raspberry Pi. The first product is an experimenter's kit, contaning an expansion board, a set of components with which to experiment, software to drive the Pi, and an instruction manual. This will be followed by a series of expansion kits, using I2C and SPI to add capabilities like ADC, DAC, PWM and stepper motor drivers.</p>
             <p>All the hardware and software will be released under open source licences.</p>
             <p>The presentation will conclude with a demonstration using hardware prototypes driven by a Raspberry Pi.</p>
             <p id="RomillyCocking" class="vcard"><a class="fn url" title="Romilly Cocking" href="http://twitter.com/romillyc">Romilly Cocking</a> spent the ten years before his 'retirement' as an agile software developer, coach and trainer. He spent the first two years of retirement experimenting with robotics. Then Raspberry Pi came along, and now Romilly works full-time running Quick2Wire.</p>

             <p><b>Note: Please aim to arrive for 18:00 - 18:20 as the event will start at 18:30 prompt.</b></p>

             <center>
                 <p><strong>Sponsored by:</strong></p>
                 <a href="http://www.designspark.com">
                     <img class="sponsor" src="/images/DS_with_RS.jpg" title="DesignSpark from RS" alt="DesignSpark from RS">
                 </a>
             </center>

date:        31st May 2012
dtstart:     2012-05-31T18:00:00Z
dtend:       2012-05-31T20:00:00Z
start:       18:00
end:         20:00
pubdate:     Wed, 16 May 2012 09:30:00 GMT
updated:     2012-05-16T09:30:00Z
location:    Centre for Creative Collaboration
isoduration: P0Y0M0DT02H00M00S
generator:   vi
registration: http://oshugkits.eventbrite.com/
upcoming:     
lanyrd:       http://lanyrd.com/2012/oshug19/

tags:
    - OSHUG
    - C4CC
    - OpenSource
    - hardware
    - opensourcehardware
    - openhardware
    - community
    - Arduino
    - RaspberryPi
    - Homesense
    - Quick2Wire
    - Tinker
    - Kits
