---
number:      2
title:       Open Hardware Licensing and Models for Sustainability
description: |
            For our second meeting we've presentations from <a href="http://twitter.com/andrewjskatz">Andrew Katz</a> on licensing 
            Open Source Hardware projects and a representative from <a href="http://payitforwardprinting.com/">Pay It Forward</a> on
            Altruistic 3D printing using <a href="http://reprap.org">RepRap</a>.

sessions: |
            <h3 id='Licensing'>Free and open source software is mainstream. Free and open hardware isn't.</h3>
            <p>
            Andrew is increasingly involved in open hardware, and considers what, 
            if anything, is different about hardware which makes open projects a challenge, 
            and whether it is possible to construct a licence, like the GPL, 
            which has a copyleft element applicable to hardware.
            </p>
            <p id='AndrewKatz'>
            <a href="http://twitter.com/andrewjskatz">Andrew Katz</a> is a partner at <a href="http://www.moorcrofts.com">Moorcrofts LLP</a>, 
            a boutique law firm in England's Thames Valley and advises a wide range of businesses on free 
            and open source related issues. He has lectured and published widely on the subject and is 
            a founder editor of the International Free and Open Source Software Law Review. 
            Before becoming a solicitor, he trained as a barrister, and moonlighted as a 
            programmer during his studies at Bar School, programming in Turbo Pascal. 
            He has released software under the GPL.
            </p>
            <object width="400" height="300"><param name="allowfullscreen" value="true" /><param name="allowscriptaccess" value="always" /><param name="movie" value="http://vimeo.com/moogaloop.swf?clip_id=12582078&amp;server=vimeo.com&amp;show_title=1&amp;show_byline=1&amp;show_portrait=0&amp;color=&amp;fullscreen=1" /><embed src="http://vimeo.com/moogaloop.swf?clip_id=12582078&amp;server=vimeo.com&amp;show_title=1&amp;show_byline=1&amp;show_portrait=0&amp;color=&amp;fullscreen=1" type="application/x-shockwave-flash" allowfullscreen="true" allowscriptaccess="always" width="400" height="300"></embed></object><p><a href="http://vimeo.com/12582078">Copy Left Licensing & Hardware, Andrew Katz</a> from <a href="http://vimeo.com/mattlucht">Matt Lucht</a> on <a href="http://vimeo.com">Vimeo</a>.</p>
            <object width="400" height="300"><param name="allowfullscreen" value="true" /><param name="allowscriptaccess" value="always" /><param name="movie" value="http://vimeo.com/moogaloop.swf?clip_id=12359856&amp;server=vimeo.com&amp;show_title=1&amp;show_byline=1&amp;show_portrait=0&amp;color=&amp;fullscreen=1" /><embed src="http://vimeo.com/moogaloop.swf?clip_id=12359856&amp;server=vimeo.com&amp;show_title=1&amp;show_byline=1&amp;show_portrait=0&amp;color=&amp;fullscreen=1" type="application/x-shockwave-flash" allowfullscreen="true" allowscriptaccess="always" width="400" height="300"></embed></object><p><a href="http://vimeo.com/12359856">Andrew Back talking with Andrew Katz of Moorcrofts LLP</a> from <a href="http://vimeo.com/mattlucht">Matt Lucht</a> on <a href="http://vimeo.com">Vimeo</a>.</p>
            <h3 id='payitforward'>Pay It Forward — Alturistic 3D Printing</h3>
            <p><a href="http://payitforwardprinting.com">Pay It Forward</a> is a 
            movement to bootstrap the <a href="http://www.thingiverse.com/">thingiverse</a>
            using <a href="http://reprap.org/wiki/RepStrap">RepStrap</a> machines to 
            print parts to help other people get started with <a href="http://reprap.org">RepRap</a> machines.
            </p>
            <object width="400" height="300"><param name="allowfullscreen" value="true" /><param name="allowscriptaccess" value="always" /><param name="movie" value="http://vimeo.com/moogaloop.swf?clip_id=12360094&amp;server=vimeo.com&amp;show_title=1&amp;show_byline=1&amp;show_portrait=0&amp;color=&amp;fullscreen=1" /><embed src="http://vimeo.com/moogaloop.swf?clip_id=12360094&amp;server=vimeo.com&amp;show_title=1&amp;show_byline=1&amp;show_portrait=0&amp;color=&amp;fullscreen=1" type="application/x-shockwave-flash" allowfullscreen="true" allowscriptaccess="always" width="400" height="300"></embed></object><p><a href="http://vimeo.com/12360094">Paul Downey chatting OSHUG with David Flanders</a> from <a href="http://vimeo.com/mattlucht">Matt Lucht</a> on <a href="http://vimeo.com">Vimeo</a>.</p>



date:        27th May 2010
dtstart:     2010-05-27T18:00:00Z
dtend:       2010-05-27T20:00:00Z
start:       18:00
end:         20:00
pubdate:     Thu, 28 May 2010 18:00:00 BST
location:    Osmosoft
isoduration: P0Y0M0DT02H00M00S
generator:   vi
registration: http://oshugsust.eventbrite.com/
upcoming:     http://upcoming.yahoo.com/event/5849274/gb/London/OSHUG-2-Open-Hardware-Licensing-and-Models-for-Sustainability/Osmosoft-Towers-Room-404/
lanyrd:       http://lanyrd.com/2010/oshug2/

tags:
    - oshug
    - OpenSource
    - hardware
    - RepRap
    - GPL
    - licensing
    - 3Dprinting
    - osmosoft
    - electronics
