---
number:     20
title:       Drones (UDB4, OpenRelief, ARDrone + Kinect)
description: |
             <p>Unmanned aerial vehicles (UAVs), or <i>drones</i>, are increasingly making the news, but when they do so it's usually because of their use in warfare. However, drones can be put to use in many other, far more positive applications. And at the twentieth OSHUG meeting we will hear talks on an experimental attitude and heading reference system (AHRS), using open source technology to build drones for use in disaster relief, and on a fun and novel method of flying drones via gesture control.</p>

sessions: |
            <h3>Using UDB4 for an Experimental AHRS</h3>
            <p id="UDB4">The <a href="http://code.google.com/p/gentlenav/" title="UAV Dev Board">UAV Development Board</a> is a very versatile development board that has been around for the past five or so years, and which has been supported by small team led by William Premerlani. The board comes with a dsPIC30F4011 microcontroller, an MMA7260 three axis accelerometer and two dual-axis Inversense IXZ500 gyroscopes. It has supported various forms of platforms ranging from inverted pendulums to multicoptors. It has primarily been a development platform for experimenters and it is in its fourth major revision.</p>
            <p>The talk intends to give a high level view of the <a href="http://code.google.com/p/gentlenav/wiki/MatrixPilot" title="MatrixPilot">MatrixPilot</a> firmware as a general introduction to autopilots, with a demonstration of the Hardware in loop simulation to show how it behaves in flight for a fixed wing aircraft.</p> 
            <p id="AnishMohammed" class="vcard"><a class="fn url" title="Anish Mohammed" href="https://twitter.com/#!/anishmohammed">Anish Mohammed</a> has been an electronics hobbyist and software hacker since his early teens. He  spent almost a decade in research and development in security and cryptography, and these days he works for the Big Five in consulting. He is a confirmed <i>UAV addict</i> who owns a dozen AHRS/Autopilots, both open and partially closed, with interests in multicopters, fixed wings and rovers.</a> 

             <h3>OpenRelief — Open Source Software and Open Hardware For Frontline Disaster Relief</h3>
             <p id="OpenRelief">This talk will explore how the <a href="http://openrelief.org">OpenRelief</a> team, inspired by challenges seen during the 2011 Tōhoku earthquake, is using Open Source Software and Open Hardware to create disaster relief tools. The first step is to develop a small drone that can take off from anywhere, recognize roads, people and smoke while also measuring weather and radiation. It can be built for less than 1,000 USD, and easily shares information with Open Source and proprietary disaster management systems. The goal is to gather critical information for relief workers on the ground, and contribute to getting aid where it is needed.</p>
             <p id="KarlLattimer">Karl Lattimer is an engineer who started early with electronics and programming, and has worked on all kinds of projects for many companies developing software to solve a wide variety of problems. He currently works for Codethink Ltd, an engineering firm based in Manchester, UK. Karl is enthusiastic about Artificial Intelligence, Computer Vision, Robotics and related engineering disciplines. He is a firm believer that we can engineer a future that is more sustainable, adaptive and integrated. His interest in OpenRelief stems from a desire to engineer solutions to the problems faced in disaster scenarios, and the desire to drive the permeation of robots into our everyday lives.</p>

             <h3>Flying an ARDrone Like a 7-year Old Child</h3>
             <p id="ardrone">Controlling a <a href="http://en.wikipedia.org/wiki/Parrot_AR.Drone" title="Parrot ARDrone">Parrot ARDrone</a> using <a href="http://www.urbiforge.org/" title="URBI">URBI</a>, python and an MS Kinect camera, allowing people to fly it by holding their arms out and pretending to be an airplane like a small child. This was in truth an exploration in how to couple independent projects and to explore and exploit the APIs presented by the kinect and the drone's software.</p>
             <p id="BenOSteen"><a class="fn url" title="Ben O'Steen" href="https://twitter.com/benosteen">Ben O'Steen</a> is a freelance developer with an interest in the fuzzy divide between physical and digital spaces, such as how we perceive and use objects differently based on how they are (re)produced, presented or controlled. Currently, he can be found working on digital library and archive projects for academic institutions, art installations and his newly completed 3d printer.</p>

             <p><b>Note: Please aim to arrive for 18:00 - 18:20 as the event will start at 18:30 prompt.</b></p>

             <center>
                 <p><strong>Sponsored by:</strong></p>
                 <a href="http://www.embecosm.com">
                     <img class="sponsor" src="/images/Embecosm.jpg" title="Embecosm: services - tools - models for embedded development" alt="Embecosm logo">
                 </a>
             </center>

date:        21st June 2012
dtstart:     2012-06-21T18:00:00Z
dtend:       2012-06-21T20:00:00Z
start:       18:00
end:         20:00
pubdate:     Thu, 7 June 2012 12:30:00 GMT
updated:     2012-06-07T12:30:00Z
location:    Centre for Creative Collaboration
isoduration: P0Y0M0DT02H00M00S
generator:   vi
registration: http://oshugdrones.eventbrite.com/
upcoming:     
lanyrd:       http://lanyrd.com/2012/oshug20/

tags:
    - OSHUG
    - C4CC
    - OpenSource
    - hardware
    - opensourcehardware
    - openhardware
    - community
    - drones
    - uav
    - kinect
    - openrelief
    - disasterrelief
    - UDB4
    - AHRS
    - ARDrone
    - URBI
