---
number:      4
title:       Community (mbed, DesignSpark, London Hackspace)
description: |
            As with open source software, the development of open source hardware is characterised by not only liberal licensing but by communities that engage in open, collaborative development. For the fourth meeting we'll be joined by speakers from three hardware communities, and gaining an insight into their operation and the motivations of the various stakeholders involved, whilst considering what open source hardware means to them.

sessions: |
            <h3>mbed - Rapid Prototyping for Microcontrollers</h3>
            <p id="mbed">Microcontrollers are getting cheaper, more powerful and more flexible, but there remains a barrier to a host of new applications; someone has to build the first prototype. There is no reason why it has to be so hard, but without the right tools, it really is. So <a title="mbed" href="http://mbed.org/">mbed</a> has tackled this by being a tool for the sole purpose of developing prototypes. We haven't had to dumb down the technology; it's all built on industry standard stuff. We've just done a lot of the groundwork for you, and made the trade-offs and choices appropriate for the task, so you don't have to. With the right tools for the job, you'll be more adventurous, inventive and productive. But best of all, you'll love building things with microcontrollers again. We built it for ourelves really!</p>
            <p id="ChrisStyles"><a title="Chris Styles" href="http://twitter.com/cstyles_arm">Chris Styles</a> graduated from Imperial College in 1996 with a degree in Electrical and Electronic Engineering. After a few years spent gaining a range of experience in the industry, he joined <a title="ARM" href="http://www.arm.com/">ARM</a> as an application engineer. For six years he helped numerous ARM partners around the world through the process of turning IP into silicon, supporting them by email and through working onsite at their offices. For the last three years Chris has been a part of a small team developing mbed. The original idea was conceived between Chris and Simon Ford as they both struggled to resolve their frustrations with applying ARM microcontroller technology outside of the embedded profession.</p>
            <h3>DesignSpark - The gateway to online resources and design support for engineers</h3>
            <p id="DesignSpark"><a title="DesignSpark" href="http://www.designspark.com">DesignSpark</a> is an interactive and social community for electronic design engineers. It allows members to share information and ideas, network with industry experts and partners, read and create reviews, gain and share knowledge and the opportunity to peruse a whole host of development kits. It also hosts the Spark Store, which provides free (as in beer) tools such as DesignSpark PCB for community members to download.</p>
            <p id="LeeStacey"><a title="Lee Stacey" href="http://twitter.com/lstacey">Lee Stacey</a> is community manager at DesignSpark and was formerly an electronics engineer with Beyerdynamic, specialising in audio amplification and processing.</p>
            <h3>London Hackspace</h3>
            <p id="LondonHackspace">The <a title="London Hackspace" href="http://london.hackspace.org.uk/">London Hackspace</a> is a non-profit, community-run <a title="hacker space" href="http://en.wikipedia.org/wiki/Hackerspace">hacker space</a> in central London. It provides a space where people who make things can come to share tools and knowledge.</p>
            <p id="HSSpeaker"><a title="t0m" href="http://wiki.hackspace.org.uk/wiki/User:T0m">Tom Doran</a> (London Hackspace)</p>

date:        23rd Sept 2010
dtstart:     2010-09-23T18:00:00Z
dtend:       2010-09-23T20:00:00Z
start:       18:00
end:         20:00
pubdate:     Fri, 2 Jul 2010 09:31:25 BST
updated:     2010-07-02T09:31:25Z
location:    Osmosoft
isoduration: P0Y0M0DT02H00M00S
generator:   vi
registration: http://oshugcommunity.eventbrite.com/
upcoming:     http://upcoming.yahoo.com/event/6658680/
lanyrd:       http://lanyrd.com/2010/oshug4/

tags:
    - oshug
    - OpenSource
    - hardware
    - opensourcehardware
    - community
    - mbed
    - ARM
    - designspark
    - rscomponents
    - londonhackspace
    - hackspace
    - hacklab
    - osmosoft
