---
number:     5 
title:       Radio (HPSDR)
description: |
            Radio spectrum is a finite resource and it should therefore come as no surprise that radio systems are a particularly hot area of research. Whilst ever more advanced schemes for modulation, digital encoding and spectrum access promise increased efficiency, step upgrades more often than not require new hardware. As has been evidenced in the evolution of mobile telephony from analogue to GSM and 2.5G (GPRS) to 3G, and similarly in the evolution of wireless computer networks. A disruptive development in radio technology promises to change this and to bring an unprecedented flexibility to radio systems, and one similar to that which programming brought to the task of machine computation. Despite, or perhaps due to being at the cutting edge there are a number of open source hardware projects concerned with developing software-defined radio (SDR) technology. As with the earliest developments in radio systems radio amateurs are once again at the forefront, and at this month's meeting we will have a presentation on the comprehensive HPSDR platform.

sessions: |
            <h3>HPSDR - High Performance Software Defined Radio</h3>
            <p id="HPSDR"><a title="HPSDR" href="http://openhpsdr.org/">HPSDR</a> is an open source (GNU type) hardware and software project intended as the "next generation" software-defined radio for radio amateurs and shortwave listeners. It is being developed by a group of software-defined radio enthusiasts around the world, and in a modular hardware fashion to help promote experimentation by both hardware and software developers.</p>
            <p id="JohnMelton"><a title="John Melton" href="http://g0orx.blogspot.com/">John Melton</a> has held an amateur radio license since 1984 when he was first licensed as N6LYT while living and working in California, and he was assigned the UK callsign of G0ORX on moving back to the UK. He became interested in developing open source software in 1990 with the launch of AMSAT Oscar 16, an amateur radio satellite with a store and forward messaging payload. He developed an open source software package to communicate with the satellite that ran on Linux (pre 1.0) and subsequently wrote an open source fully automated satellite ground station software package in Java. John has been a software engineer since 1970 when he was employed by Burroughs Corporation, and for the last 14 years he has worked for Sun Microsystems who were acquired by Oracle this year.</p>

            <h3>Open Discussion - Ideas for Future Meetings</h3>
            <p id="OpenDiscussion"> Themes, speakers, venues - it's all up for grabs! Have your say and help shape future OSHUG meetings. Offer to present, suggest a speaker or sit quietly until it's time to cross the road to the pub...</p>

date:        21st Oct 2010
dtstart:     2010-10-21T18:00:00Z
dtend:       2010-10-21T20:00:00Z
start:       18:00
end:         20:00
pubdate:     Tues, 12 Oct 2010 21:31:25 BST
location:    Osmosoft
isoduration: P0Y0M0DT02H00M00S
generator:   vi
registration: http://oshugradio.eventbrite.com/
upcoming:     http://upcoming.yahoo.com/event/7182024/
lanyrd:       http://lanyrd.com/2010/oshug-october/

tags:
    - oshug
    - OpenSource
    - hardware
    - opensourcehardware
    - community
    - SDR
    - software-definedradio
    - amateurradio
    - hamradio
    - electronics
    - osmosoft
